adminPassword: password
customLdifFiles:
  01-suomitek-appboard-dev.ldif: |-
    dn: ou=People,dc=example,dc=org
    objectClass: organizationalUnit
    ou: People
    
    dn: cn=jane,ou=People,dc=example,dc=org
    objectClass: person
    objectClass: inetOrgPerson
    sn: doe
    cn: jane
    mail: suomitek-appboard-operator-ldap@example.org
    userpassword: password
    
    dn: cn=john,ou=People,dc=example,dc=org
    objectClass: person
    objectClass: inetOrgPerson
    sn: doe
    cn: john
    mail: suomitek-appboard-user-ldap@example.org
    userpassword: password
    
    # Group definitions.
    dn: ou=Groups,dc=example,dc=org
    objectClass: organizationalUnit
    ou: Groups
    
    dn: cn=admins,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: admins
    member: cn=john,ou=People,dc=example,dc=org
    member: cn=jane,ou=People,dc=example,dc=org
    
    dn: cn=developers,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: developers
    member: cn=jane,ou=People,dc=example,dc=org

    dn: cn=kubeapps-operators,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: kubeapps-operators
    member: cn=jane,ou=People,dc=example,dc=org

    dn: cn=suomitek-appboard-users,ou=Groups,dc=example,dc=org
    objectClass: groupOfNames
    cn: suomitek-appboard-users
    member: cn=john,ou=People,dc=example,dc=org
