# suomitek-appboard-operator has cluster-admin
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suomitek-appboard-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
# dex does not allow group claims when using the static connector
# https://github.com/dexidp/dex/issues/1080
# So instead use the testing of groups with the ldap access only.
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:suomitek-appboard-operator@example.com
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:suomitek-appboard-operators
# suomitek-appboard-user has access only to the suomitek-appboard-user-namespace namespace
---
kind: Namespace
apiVersion: v1
metadata:
  name: suomitek-appboard-user-namespace
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suomitek-appboard-user
  namespace: suomitek-appboard-user-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:suomitek-appboard-user@example.com
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:suomitek-appboard-users
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suomitek-appboard-user-apprepositories-read
  namespace: suomitek-appboard-user-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: suomitek-appboard:suomitek-appboard:apprepositories-read
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:suomitek-appboard-user@example.com
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:suomitek-appboard-users
---
# Currently unnecessary (when suomitek-appboard operators are already cluster-admin) but
# included to be explicit and plan to replace cluster-admin for suomitek-appboard
# operators with something less privileged.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: suomitek-appboard-operator-apprepositories-write
  namespace: suomitek-appboard-user-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: suomitek-appboard:suomitek-appboard:apprepositories-write
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: oidc:suomitek-appboard-operator@example.com
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:suomitek-appboard-operators

