apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: suomitek-appboard-service-catalog-browse
rules:
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - clusterservicebrokers
  - clusterserviceclasses
  - clusterserviceplans
  verbs:
  - list
