apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubeapps-service-catalog-write
rules:
- apiGroups:
  - servicecatalog.k8s.io
  resources:
  - serviceinstances
  - servicebindings
  verbs:
  - create
  - delete
