apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suomitek-appborad.apprepository-jobs-cleanup.fullname" . }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:{{ include "suomitek-appborad.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.apprepository-jobs-cleanup.fullname" . }}
