{{- if not (.Capabilities.APIVersions.Has "suomitek.com/v1alpha1") -}}
# The condition above will be true if another instance of Suomitek-appboard is
# already installed
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apprepositories.suomitek.com
  annotations:
    "helm.sh/hook": crd-install
  labels:{{ include "suomitek-appboard.extraAppLabels" $ | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" $ }}
spec:
  group: suomitek.com
  scope: Namespaced
  names:
    kind: AppRepository
    plural: apprepositories
    shortNames:
      - apprepos
  version: v1alpha1
{{- end -}}
