{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "suomitek-appboard.apprepository.fullname" . }}
  labels:{{ include "suomitek-appboard.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - get
      - list
      - update
      - watch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
  - apiGroups:
      - suomitek.com
    resources:
      - apprepositories
      - apprepositories/finalizers
    verbs:
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "suomitek-appboard.apprepository.fullname" . }}
  labels:{{ include "suomitek-appboard.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "suomitek-appboard.apprepository.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "suomitek-appboard.apprepository.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
# Define role, but no binding, so users can be bound to this role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-repositories-read
rules:
  - apiGroups:
      - suomitek.com
    resources:
      - apprepositories
    verbs:
      - list
      - get
---
# Define role, but no binding, so users can be bound to this role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-repositories-write
rules:
  - apiGroups:
      - suomitek.com
    resources:
      - apprepositories
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
---
# The Kubeapps app repository controller can read and watch its own
# AppRepository resources cluster-wide. The read and write cluster-roles can
# also be bound to users in specific namespaces as required.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "suomitek-appboard:{{ .Release.Namespace }}:apprepositories-read"
  labels:{{ include "suomitek-appboard.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" . }}
rules:
  - apiGroups:
      - suomitek.com
    resources:
      - apprepositories
      - apprepositories/finalizers
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "suomitek-appboard:controller:{{ .Release.Namespace }}:apprepositories-read"
  labels:{{ include "suomitek-appboard.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubeapps:{{ .Release.Namespace }}:apprepositories-read"
subjects:
  - kind: ServiceAccount
    name: {{ template "suomitek-appboard.apprepository.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubeapps:{{ .Release.Namespace }}:apprepositories-write"
  labels:{{ include "suomitek-appboard.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" . }}
rules:
  - apiGroups:
      - suomitek.com
    resources:
      - apprepositories
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
{{- end -}}
