apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suomitek-appborad.apprepository.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.apprepository.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suomitek-appborad.apprepository-job-postupgrade.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.apprepository.fullname" . }}
