apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suomitek-appboard.apprepository.fullname" . }}
  labels:{{ include "suomitek-appboard.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suomitek-appboard.apprepository-job-postupgrade.fullname" . }}
  labels:{{ include "suomitek-appboard.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appboard.apprepository.fullname" . }}
