apiVersion: v1
kind: Service
metadata:
  name: {{ template "suomitek-appborad.assetsvc.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.assetsvc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "suomitek-appborad.assetsvc.fullname" . }}
    release: {{ .Release.Name }}
