{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "suomitek-appborad.db-secret-jobs-cleanup.fullname" . }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:{{ include "suomitek-appborad.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.db-secret-jobs-cleanup.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "suomitek-appborad.db-secret-jobs-cleanup.fullname" . }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "-10"
  labels:{{ include "suomitek-appborad.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.db-secret-jobs-cleanup.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "suomitek-appborad.db-secret-jobs-cleanup.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "suomitek-appborad.db-secret-jobs-cleanup.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
