{{- if gt (len .Values.clusters) 0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "suomitek-appborad.kubeops-config.fullname" . }}
  labels:
    app: {{ template "suomitek-appborad.kubeops-config.fullname" . }}
    chart: {{ template "suomitek-appborad.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  additional-clusters.conf: |-
{{ .Values.clusters | toPrettyJson | indent 4 }}
{{- end -}}
