{{- if .Values.useHelm3 -}}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "suomitek-appborad.kubeops.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - "suomitek.com"
    resources:
      - apprepositories
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "suomitek-appborad.kubeops.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "suomitek-appborad.kubeops.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "suomitek-appborad.kubeops.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.allowNamespaceDiscovery }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubeapps:controller:kubeops-ns-discovery-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubeapps:controller:kubeops-ns-discovery-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubeapps:controller:kubeops-ns-discovery-{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "suomitek-appborad.kubeops.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- if .Values.featureFlags.operators }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "kubeapps:controller:kubeops-operators-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
rules:
  - apiGroups:
      - packages.operators.coreos.com
    resources:
      - packagemanifests/icon
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kubeapps:controller:kubeops-operators-{{ .Release.Namespace }}"
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "kubeapps:controller:kubeops-operators-{{ .Release.Namespace }}"
subjects:
  - kind: ServiceAccount
    name: {{ template "suomitek-appborad.kubeops.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
{{- end -}}
{{- end }}{{/* matches useHelm3 */}}
