{{- if .Values.useHelm3 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "suomitek-appborad.kubeops.fullname" . }}
  labels:{{ include "kubeapps.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.kubeops.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
    release: {{ .Release.Name }}
{{- end }}{{/* matches useHelm3 */}}
