{{- if .Values.useHelm3 -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "suomitek-appborad.kubeops.fullname" . }}
  labels:{{ include "kubeapps.extraAppLabels" . | nindent 4 }}
    app: {{ template "suomitek-appborad.kubeops.fullname" . }}
    app.kubernetes.io/name: {{ template "suomitek-appborad.name" . }}
{{- end }}{{/* matches useHelm3 */}}
