apiVersion: v1
name: suomitek-appboard
version: 3.9.0
appVersion: DEVEL
description: Suomitek-appboard is a dashboard for your Kubernetes cluster that makes it easy to deploy and manage applications in your cluster using Helm
icon: https://raw.githubusercontent.com/suomitek/suomitek-appboard/master/docs/img/logo.png
keywords:
  - helm
  - dashboard
  - service catalog
  - deployment
home: https://suomitek.com
sources:
  - https://github.com/suomitek/suomitek-appboard
maintainers:
  - name: Bitnami
    email: containers@suomitek.com
# 2.14+ required https://github.com/suomitek/suomitek-appboard/issues/1185
tillerVersion: ">=2.14.0"
annotations:
  category: Infrastructure
